version: "0.5"

processes:
  discord-bot:
    command: "python main.py"
    working_dir: "."
    environment:
      - "PYTHONUNBUFFERED=1"
    availability:
      restart: "always"
      backoff_seconds: 5
      max_restarts: 500
    log_file: "/tmp/discord-bot.log"

log_level: info
is_strict: false